spring:
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/delivery
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
security:
  jwt:
    secretKey: sdfjihoienvo948hvoi348h0v3b9wurfhb0eihfb08efd9bdubhxcnbvosibon